steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  # Reverted to standard $PROJECT_ID for the built-in substitution
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest'
  - '.'
  id: 'Build Docker Image'

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  # Reverted to standard $PROJECT_ID
  args: [ 'push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest' ]
  id: 'Push to Artifact Registry'

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:latest'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}' # This is the Cloud Run service name
  - '--image'
  # Reverted to standard $PROJECT_ID
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--ingress=all'
  - '--allow-unauthenticated'
  # $PROJECT_ID is the standard way to reference the project for this gcloud argument
  - '--project=$PROJECT_ID'
  id: 'Deploy to Cloud Run'

# (Optional) Tag the image with the commit SHA for versioning
- name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:latest'
  entrypoint: gcloud
  args:
  - 'artifacts'
  - 'docker'
  - 'tags'
  - 'add'
  # Reverted to standard $PROJECT_ID
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest'
  # SHORT_SHA is a built-in, $SHORT_SHA or ${_SHORT_SHA} might also work, but let's keep it simple.
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${SHORT_SHA}'
  id: 'Tag Image'
# Store images in Artifact Registry
images:
# Reverted to standard $PROJECT_ID
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest'

substitutions:
  # These will be provided by the Makefile's 'gcloud builds submit ... --substitutions' flag
  # Cloud Build also automatically provides PROJECT_ID, COMMIT_SHA, SHORT_SHA etc.
  # No need to list PROJECT_ID here as it's a built-in variable.
  _SERVICE_NAME: 'hello-tool-base' # Default if not overridden by Makefile
  _REGION: 'us-central1' # Default if not overridden by Makefile
  _ARTIFACT_REGISTRY_REPO: 'my-go-apps' # Default if not overridden by Makefile

options:
  logging: CLOUD_LOGGING_ONLY
