steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  # Hardcoded most of the path, only _SERVICE_NAME is from substitution for this test.
  # Replace YOUR_PROJECT_ID with archie-bot-250509
  # Replace YOUR_REGION with us-central1
  # Replace YOUR_ARTIFACT_REGISTRY_REPO with my-go-apps
  - 'us-central1-docker.pkg.dev/archie-bot-250509/my-go-apps/${_SERVICE_NAME}:latest'
  - '.'
  id: 'Build Docker Image'

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-central1-docker.pkg.dev/archie-bot-250509/my-go-apps/${_SERVICE_NAME}:latest' ]
  id: 'Push to Artifact Registry'

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:latest'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}' # This is the Cloud Run service name
  - '--image'
  - 'us-central1-docker.pkg.dev/archie-bot-250509/my-go-apps/${_SERVICE_NAME}:latest'
  - '--region'
  - '${_REGION}' # _REGION is still used here, which is fine.
  - '--platform'
  - 'managed'
  - '--ingress=all'
  - '--allow-unauthenticated'
  # $PROJECT_ID is fine here as it's a direct gcloud arg.
  - '--project=$PROJECT_ID'
  id: 'Deploy to Cloud Run'

# (Optional) Tag the image with the commit SHA for versioning
- name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:latest'
  entrypoint: gcloud
  args:
  - 'artifacts'
  - 'docker'
  - 'tags'
  - 'add'
  - 'us-central1-docker.pkg.dev/archie-bot-250509/my-go-apps/${_SERVICE_NAME}:latest'
  - 'us-central1-docker.pkg.dev/archie-bot-250509/my-go-apps/${_SERVICE_NAME}:${SHORT_SHA}'
  id: 'Tag Image'

# Store images in Artifact Registry
images:
- 'us-central1-docker.pkg.dev/archie-bot-250509/my-go-apps/${_SERVICE_NAME}:latest'

substitutions:
  # _SERVICE_NAME, _REGION, _ARTIFACT_REGISTRY_REPO are passed from the Makefile.
  # For this test, only _SERVICE_NAME and _REGION are actively used by the YAML in critical spots.
  _SERVICE_NAME: 'hello-tool-base' # Default if not overridden by Makefile
  _REGION: 'us-central1' # Default if not overridden by Makefile
  _ARTIFACT_REGISTRY_REPO: 'my-go-apps' # Default, not used in image strings for this test

options:
  logging: CLOUD_LOGGING_ONLY
